### PR TITLE
Add fix for booking mobile

### PR DESCRIPTION
**Pull request by casperjureskog**
**PT Story:** https://www.pivotaltracker.com/story/show/144276745

**Changes proposed in this PR:**

* Adds dubbel book check
* Adds adjust request spec 
* Adds att title to the project 

**What I have learned working on this feature:**
Its easier to fix the logic in rails then ionic

### CODE REVIEW

**Comment by AmberWilkie** [comment]
Is this ready? There's no description.

**Review by casperjureskog — COMMENTED** [review]
Hi Amber fix it late last night :-) now I aded the descriptions

**Review by AmberWilkie — CHANGES_REQUESTED** [review]
I'd like to see a sad path for both of those API endpoints - what do the error messages look like? Otherwise, looks pretty great to me!

**Comment by AmberWilkie** [comment]
Ok good, but can you get it to return a more helpful message. Imagine someone working on the front-end. When they do this wrong, they are just going to get "message: error". Maybe it could return something like `facility does not exist`. Is there a way to auto-generate an error - like `@factory.errors.full_messages`?

**Review by AmberWilkie — APPROVED** [review]
Nice work.

**Pull request merged**
