### PR TITLE
Admin sign up

### PR DESCRIPTION
**Pull request by fottander**
**PT Story:** https://www.pivotaltracker.com/story/show/144025105

**Changes proposed in this PR:**

* Adds sign up view and form
* Adds index page
* Adds button to sign up from index

**What I have learned working on this feature:**
To use devise to generate necessary files

### CODE REVIEW

**Review by diraulo — COMMENTED** [review]
1. I don't think that this being an admin app, you should allow people to openly sign up to it. I would probably have set it up with a super admin user that can register/approve new users as admin

2. How about having a generic class `User` with an attribute `admin` that can be set to `true` / `false` - This way if you decide to expand your application later on to allow other users to sign-up/in you can do so without having to generate a lot of duplicated functionality/code. 🤔 

That said, one could argue that we shouldn't be thinking about the future now and only focus on the needs of the application right now...

**Comment by fottander** [comment]
Good point for sure. 
We will have to look into this, i´ve put it in our google docs and fabian and i will see how we will move on.

**Comment by diraulo** [comment]
Hmm @fottander you merged the PR without approval from anyone? I thought we were discussing about this generic class idea? 🤔

**Comment by Scharrre97** [comment]
No @diraulo , that's my bad. Sorry about that, I'm to fast :/ my suggest was that we made a fix PR when you guys have finish your discuss.  Thx

**Comment by tochman** [comment]
Yes, please do not rush this. Apart from the class discussion, I see a lot of files in this PR that are not needed. Also a lot of erb files.

**Comment by diraulo** [comment]
Unless a PR is a blocker to another feature, I don't see any reason for rushing to merge it. Especially when there's a pending discussion.

**Comment by fottander** [comment]
It was a blocker for the devise token auth which we started on. 
Fabian and I are discussing what the best action is right now.

**Comment by diraulo** [comment]
As far as I know you can setup `devise_token_auth` without `devise` on an application. Unless i'm missing something here, so not really a blocker. You're only using `devise_token_auth` for the API part of the application

**Comment by fottander** [comment]
Yeah , hard to know be sure of that though. Can we do a super admin later on or are there gonna be problems with that implementation since we have this code right now? 
Is it just as easy to implement it later as it would have been to do it right away?

**Pull request merged**
